version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eps-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 65cristofer
      MYSQL_DATABASE: sistema_emprendedores_chiquimula
      MYSQL_USER: eps_user
      MYSQL_PASSWORD: eps_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
